# Generated by Django 3.1.2 on 2020-10-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_post', '0002_post_of_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default=1),
        ),
    ]
