# Generated by Django 3.1.2 on 2020-10-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_post', '0003_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='domain',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
